# Generated by Django 3.1.5 on 2021-01-15 18:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='create',
        ),
        migrations.AddField(
            model_name='product',
            name='create_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='create_at'),
            preserve_default=False,
        ),
    ]
