# Generated by Django 3.1.5 on 2021-01-15 18:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210115_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='create',
        ),
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created at'),
            preserve_default=False,
        ),
    ]
